name: "Release"

on:
  push:
    branches:
      - master

jobs:
  release-draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create prerelease
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.release-drafter.outputs.body }}
          prerelease: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ steps.release-drafter.outputs.tag_name }}
          replacesArtifacts: true
          allowUpdates: true
          makeLatest: true
          name: ${{ steps.release-drafter.outputs.name }}
