name: Test release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

env:
  BUILD_DIR: "cmake-build-release"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ env.BUILD_DIR }}
    steps:
      - run: echo "Exposing env vars"

  build-release:
    uses: stolex1y/sorting-on-tape/.github/workflows/build.yml@master
    needs: vars
    with:
      build_type: "Release"
      build_dir: ${{ needs.vars.outputs.build_dir }}

  test-release:
    runs-on: ubuntu-latest
    needs: [ vars, build-release ]
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.vars.outputs.build_dir }}
          path: .

      - name: Extract build archive
        run: |
          tar -xzf "$BUILD_DIR.tar.gz"
          sudo chmod -R 755 $BUILD_DIR

      - name: Test
        run: |
          cd $BUILD_DIR
          ctest --timeout 10 --output-on-failure --schedule-random -j 2

      - name: Upload build logs if failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test release build
          path: ${{ needs.vars.outputs.build_dir }}/test
