name: "Verify type labels"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify-pr-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'major, minor, fix, documentation, workflows, tests, config, skip-changelog'
